### ISSUE TITLE
In V3, deleting  an object requires ownership of the object and editor rights to the library

### ISSUE THREAD

**Issue by elv-marc** [eluv-io/contracts#105]
One change made in v3 is that the delete method for a content object is not called on the contract of that object, but instead on the library. That  call requires editor rights on the library.
Currently there is not UI to grant editor right to a user or a group, so the result is that only the library owner as such rights.

Deleting  an object requires ownership of the object and editor rights to the library, so only objects which are owned by the library owner can be deleted without advance intervention.

The simplest work-around for an object owner to delete an object is to transfer ownership to library owner and ask library owner to then make the object deletion.

Alternatively, editor rights to the library can be manually set using direct contract calls.

**Comment by elv-serban** [comment]
Confirmed this behavior.

Work around in the fabric browser:
- in library info
- click into the contract
- call `setGroupAccess` with arguments address of content admins, 2, 2

After setting access, delete works.

**Comment by elv-serban** [comment]
This is solved by adding the Manage capability in the Fabric Browser that will set object-level Edit on the library object.
